import { defineField, defineType } from 'sanity';

export const homePage = defineType({
  name: 'homePage',
  title: 'Homepage',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content & Layout', default: true },
    { name: 'hero', title: 'Hero Banner' },
    { name: 'quotes', title: '💬 Client Quotes & Photos' },
    { name: 'popup', title: 'Floating Tool Popup' },
    { name: 'seo', title: 'SEO & Metadata' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Page Title (Internal)',
      type: 'string',
      initialValue: 'Homepage',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),

    // Direct Client Quotes & Photos Customization
    defineField({
      name: 'quote1ClientName',
      title: 'Quote 1 — Client Name',
      type: 'string',
      initialValue: 'Shelia',
      group: 'quotes',
    }),
    defineField({
      name: 'quote1Quote',
      title: 'Quote 1 — Large Quote',
      type: 'text',
      rows: 2,
      initialValue: '“We\'ve gone from zero postings. I never post.”',
      group: 'quotes',
    }),
    defineField({
      name: 'quote1Timeframe',
      title: 'Quote 1 — Subtitle / Timeframe',
      type: 'string',
      initialValue: 'Three months into working together',
      group: 'quotes',
    }),
    defineField({
      name: 'quote1Paragraph',
      title: 'Quote 1 — Story Paragraph',
      type: 'text',
      rows: 3,
      initialValue: 'She told me no for two months. Too busy, too nervous, not her thing. We started in June anyway. By September, a distant contact\'s barber saw her content, which immediately led to a dentist contracting her for three commercial projects and a custom home build.',
      group: 'quotes',
    }),
    defineField({
      name: 'quote1Photo',
      title: 'Quote 1 — Client Photo (Shelia)',
      type: 'image',
      options: { hotspot: true },
      group: 'quotes',
      description: 'Upload Shelia or commercial architecture portrait image.',
    }),
    defineField({
      name: 'quote1Tag',
      title: 'Quote 1 — Photo Badge / Tag',
      type: 'string',
      initialValue: 'Commercial Architecture & Building',
      group: 'quotes',
    }),
    defineField({
      name: 'quote1CtaText',
      title: 'Quote 1 — CTA Text',
      type: 'string',
      initialValue: 'See how content can compound for you',
      group: 'quotes',
    }),

    defineField({
      name: 'quote2ClientName',
      title: 'Quote 2 — Client Name',
      type: 'string',
      initialValue: 'Roslyn',
      group: 'quotes',
    }),
    defineField({
      name: 'quote2Quote',
      title: 'Quote 2 — Large Quote',
      type: 'text',
      rows: 2,
      initialValue: '“I had no idea. I\'m so excited.”',
      group: 'quotes',
    }),
    defineField({
      name: 'quote2Timeframe',
      title: 'Quote 2 — Subtitle / Timeframe',
      type: 'string',
      initialValue: 'Hearing her enrollment number out loud',
      group: 'quotes',
    }),
    defineField({
      name: 'quote2Paragraph',
      title: 'Quote 2 — Story Paragraph',
      type: 'text',
      rows: 3,
      initialValue: 'Her Harrisburg campus had room for 125 children and sat at 28% full. We started in March. By June 30 it was at 56%, and she had never run marketing of any kind before that. She found out on a call with me, because I stopped and asked her for the number.',
      group: 'quotes',
    }),
    defineField({
      name: 'quote2Photo',
      title: 'Quote 2 — Client Photo (Roslyn)',
      type: 'image',
      options: { hotspot: true },
      group: 'quotes',
      description: 'Upload Roslyn or campus enrollment portrait image.',
    }),
    defineField({
      name: 'quote2Tag',
      title: 'Quote 2 — Photo Badge / Tag',
      type: 'string',
      initialValue: 'Campus Enrollment & Growth',
      group: 'quotes',
    }),
    defineField({
      name: 'quote2CtaText',
      title: 'Quote 2 — CTA Text',
      type: 'string',
      initialValue: 'See what this could look like for you',
      group: 'quotes',
    }),

    // Hero Dedicated Customization
    defineField({
      name: 'heroHeadline',
      title: 'Hero Main Headline',
      type: 'string',
      initialValue: 'Marketing for people too busy doing the work.',
      group: 'hero',
      description: 'The large serif headline on the homepage hero.',
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Hero Subheadline',
      type: 'text',
      rows: 3,
      initialValue: 'I turn operating insight into market authority. You talk for 45 minutes; I build the narrative backbone, voice bank, and demand engine that puts you in front of the right buyers.',
      group: 'hero',
    }),
    defineField({
      name: 'heroImage',
      title: 'Sheri / Presenter Cutout Photo',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
      description: 'The photo of Sheri pointing or presenting.',
    }),
    defineField({
      name: 'heroBackgroundImage',
      title: 'Hero Background Texture / Image',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroPrimaryCta',
      title: 'Hero Primary CTA Text',
      type: 'string',
      initialValue: 'Book a 20-min gap check',
      group: 'hero',
    }),
    defineField({
      name: 'heroSecondaryCta',
      title: 'Hero Secondary CTA Text',
      type: 'string',
      initialValue: 'Tell me what feels heavy',
      group: 'hero',
    }),

    // Floating Tool Popup on Homepage
    defineField({
      name: 'popupEnabled',
      title: 'Enable Bottom-Right Tool Popup',
      type: 'boolean',
      initialValue: true,
      group: 'popup',
    }),
    defineField({
      name: 'popupBadge',
      title: 'Popup Eyebrow Badge',
      type: 'string',
      initialValue: 'free tool',
      group: 'popup',
    }),
    defineField({
      name: 'popupHeadline',
      title: 'Popup Headline',
      type: 'string',
      initialValue: 'Are your B2B Emails Hit or Miss? Transform them in 3 seconds for free!',
      group: 'popup',
    }),
    defineField({
      name: 'popupButtonText',
      title: 'Popup Button Label',
      type: 'string',
      initialValue: 'fix my email',
      group: 'popup',
    }),

    // Flexible Elementor-like Page Builder Section List
    defineField({
      name: 'sections',
      title: 'Page Sections (Drag, Add, Reorder or Remove)',
      type: 'array',
      group: 'content',
      description: 'Rearrange, disable, or add subsections to customize the layout like a visual builder.',
      of: [
        { type: 'whoWeServeSection' },
        { type: 'clientStoriesSection' },
        { type: 'metricsSection' },
        { type: 'videoCarouselSection' },
        { type: 'pricingSection' },
        { type: 'comparisonSection' },
        { type: 'faqSection' },
        { type: 'closingCtaSection' },
        { type: 'richTextSection' },
        { type: 'mediaCalloutSection' },
        { type: 'popupToolSection' },
      ],
    }),


    // SEO
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      group: 'seo',
      initialValue: 'GLS. — Marketing for People Too Busy Doing the Work',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      initialValue: 'Content and messaging advisory for founders, operators, and in-house teams by Sheri Otto.',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'heroHeadline',
      media: 'heroImage',
    },
  },
});
